name: DiscordAuthentication
main: com.johnymuffin.beta.discordauth.DiscordAuthentication
author: JohnyMuffin
version: 1.1.4
depend: [DiscordCore]
commands:
  discordauth:
    description: Basic DiscordAuth commands
    usage: /<command>
  link:
    description: Link your Minecraft account to your Discord account
    usage: /<command> <code>
  unlink:
    description: Unlink your Minecraft account from your Discord account
    usage: /<command>